import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "../components/Navbar";
import Banner from "../components/Banner";
import Nav from "../components/Nav";
import Services from "../components/Services";
import Work from "../components/Work";
import Contact from "../components/Contact";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-site bg-no-repeat bg-cover overflow-hidden">
        <Navbar />
        <Banner />
        <Nav />
        <Services />
        <Work />
        <Contact />
      </main>
    </div>
  );
}
